### PR TITLE
add functions for formatting in decimal notation

### PR DESCRIPTION
**Pull request by myserg**
Add StringDecimal and AppendDecimal convenience functions.

### CODE REVIEW

**Comment by woodsbury** [comment]
Hi, thanks for the PR.

I'm a bit hesitant to merge these changes, at first glance it looks like something similar can be done using the existing `.Append()` function.

For example, instead of `.AppendDecimal(x)` you could say `.Append(x, "f")` or `.Append(x, ".16f")` if you need a suitable precision (though I understand this clamps the output to the number of digits).

Do you have anything you could share about the goal of these changes and what the issue is with the current functionality?

**Comment by myserg** [comment]
The goal is to allow a number to be formatted without knowing its precision in advance. You can do it for floats with strconv.FormatFloat(,,-1,), but for Decimal you cannot. Please suggest another solution if you don't like these functions, but this functionality is critical. For example, parsing a string into a number, doing some manipulation with it and then converting it back into a string is a very common operation in my practice.

**Comment by woodsbury** [comment]
I can appreciate that the limitations that the standard format strings can make controlling exactly how you want your values to be output difficult, and the fact the standard library provides an alternative that does allow you to do what you want for float64s is a good reason to support it here too. I'd like to avoid adding new functions for formatting if possible, but what I'm thinking is if we instead extend the format string that `.Append()` accepts to allow specifying that you want the equivalent of what -1 means in `strconv.FormatFloat()` - so, for example, if you could call `.Append(x, ".-f")` where the `-` means "use the smallest number of digits" (I don't know if `-` is the best character for this, I'm just using it as an example here). Does that sound like it would help with your use case?

With the current version of the library, another thing to note is that JSON marshalling allows more significant digits before it switches to the exponent notation for numbers. This may or may not be helpful to you depending on the kinds of numbers you need to handle, but thought I'd mention it in case it was any help in the meantime before we can make other changes. For example, here you can see that `fmt.Printf` chooses the exponent notation but `json.Marshal` will still use decimal notation: https://play.golang.com/p/0Ram3OPOUIu

If I remember correctly, the cut-off for JSON numbers is 20 significant digits and up to 6 decimal places before it changes to exponent notation.

**Comment by myserg** [comment]
Yes, format string extension will work too ( ".-1f"? better than just minus sign). As for JSON/Text marshaling, usually, if a project only needs decimal notation, it's also used for such marshaling. For example, no one wants to see asset prices in scientific notation. It's best to somehow allow the library client to choose the notation both when creating strings and when marshaling into text formats.

**Comment by woodsbury** [comment]
I've pushed a commit to the branch `shortest-format` with a change to `.Append()` that allows you to ask for the shortest representation. I used the `*` character as the way to ask for it - my thinking being that `*` already has a special meaning as a precision in a format string (to get the precision from the next argument to `Printf()`) but that isn't useful to `.Append()` since it doesn't take any additional format arguments, so by reusing it for this I can't be clashing with anything else that might come up in the future (as unlikely as that might be).

I'm keen to hear what you think of the changes.

**Comment by myserg** [comment]
Well, now you can format a number using Append, but fmt.Sprintf won't work because '*' is used and it expects a second argument. Maybe it's worth using just 'F' instead of '*', and then fmt.Sprintf will work? Or am I missing something?

**Comment by woodsbury** [comment]
You're correct, you can't format a number (float64 or decimal128) the way you want using the `Printf` family of functions - they don't provide any way to ask for the smallest precision for the `f` style format.

**Comment by myserg** [comment]
It seems best to add a new verb (e.g. `%c`) which will be processed either in `Decimal.Format` or in `Decimal.Append`. The standard library is already evolving this way (`fmt.Errorf ` supports `%w` but `fmt.Printf` does not).

**Comment by woodsbury** [comment]
It wasn't my intent to support it in Printf - the goal of this library has been to mimic the behaviour of float64 for those use cases, so anything you can't do with a float64 you can't do for a decimal128 either.

**Comment by myserg** [comment]
I don't quite understand what float64 has to do with it. It's a completely different type that can't do what Decimal does. If we follow your logic, then we need to provide an analog of `strconv.FormatFloat`. In my opinion, this is too cumbersome a solution, but this will also work just fine. 
The solution "change only `Append`, but `Format` won't work" doesn't seem complete to me, because any user of the library certainly expects that verbs for `Append` will work for `fmt.Formatter` interface as well.

**Comment by woodsbury** [comment]
The aim of this library is to act the same way `float64` does, as much as is possible within the limitations of the Go language. This is something you can't do with `Printf` for `float64` so adding it here would be a difference, and changing how `%F` behaves would break that compatibility we're aiming for (and also break compatibility with previous version of this module).

I do agree with you that a format string working one way in `Append` and another in `Format` is a bit strange and could be confusing. I certainly wouldn't expect there to ever be a verb that worked in one and not the other, which was why I was favouring the precision value instead. For `*`,  you can sort of think of it like there being an implicit second format argument to `Append` that tells it the minimum number of digits it needs (since it's not possible to pass an actual second argument so `*` could never get anything else). I admit that is still a little arbitrary; it would maybe make a bit more sense if there was a way to get the number you needed to pass to `Printf` when using `*` to have it perform the same behaviour, but I'm not sure that's possible currently.

Perhaps the best way to keep the compatibility we have but provide this functionality is to just add new top-level `Append` and `Format` functions that work the same way that `strconv.AppendFloat` and `strconv.FormatFloat` do. It sort of makes `Decimal.Append` redundant, but the standard library adding its `fmt.Appendf` already kind of made it redundant anyway. I can make that change on a new branch so we can at least see what it would look like.

**Comment by myserg** [comment]
Honestly, I don't see the need for such functions, but they would also work as a solution for the "make a string" and "append bytes" use cases. Of course, using `*` (without additional argument) in the interface of these functions is still a bad idea, because it confuses the user accustomed to the `fmt` package (and libc).

**Comment by woodsbury** [comment]
I have a change on the branch `strconv-funcs` that introduces a new top level `Append` and `Format` function that take similar arguments to `strconv.AppendFloat` and `strconv.FormatFloat` - including being able to provide a precision of -1 to represent "shortest number of digits" for any of the formats.

**Comment by myserg** [comment]
Everything works as expected, thank you. Please merge.

**Comment by woodsbury** [comment]
The new functions have been merged into the main branch. Thanks.

**Pull request closed without merging**
